# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_option_prices <- function(num_simulations, S0, K1, K2, K3, sigma, r, T, barrier, is_down_and_out) {
    .Call('_AsianOpt_simulate_option_prices', PACKAGE = 'AsianOpt', num_simulations, S0, K1, K2, K3, sigma, r, T, barrier, is_down_and_out)
}

